### ISSUE TITLE
I get error when i use npm start

### ISSUE THREAD

**Issue by drupalshift** [emilioastarita/lyricfier#10]
Here is the error 

```
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! lyricfier@0.2.1 prestart: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the lyricfier@0.2.1 prestart script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lyricfier package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lyricfier
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lyricfier
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle lyricfier@0.2.1~prestart: lyricfier@0.2.1
6 verbose lifecycle lyricfier@0.2.1~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle lyricfier@0.2.1~prestart: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/drupalshift/Desktop/lyricfier/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
8 verbose lifecycle lyricfier@0.2.1~prestart: CWD: /home/drupalshift/Desktop/lyricfier
9 silly lifecycle lyricfier@0.2.1~prestart: Args: [ '-c', 'tsc' ]
10 silly lifecycle lyricfier@0.2.1~prestart: Returned: code: 2  signal: null
11 info lifecycle lyricfier@0.2.1~prestart: Failed to exec prestart script
12 verbose stack Error: lyricfier@0.2.1 prestart: `tsc`
12 verbose stack Exit status 2
12 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:877:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid lyricfier@0.2.1
14 verbose cwd /home/drupalshift/Desktop/lyricfier
15 error Linux 4.4.0-21-generic
16 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
17 error node v6.9.1
18 error npm  v3.10.8
19 error code ELIFECYCLE
20 error lyricfier@0.2.1 prestart: `tsc`
20 error Exit status 2
21 error Failed at the lyricfier@0.2.1 prestart script 'tsc'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the lyricfier package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     tsc
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs lyricfier
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls lyricfier
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

```

**Comment by buszk** [comment]
Yes, I got the same problem on a Mac environment.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.3.12
3 info using node@v7.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle lyricfier@0.2.1~prestart: lyricfier@0.2.1
6 verbose lifecycle lyricfier@0.2.1~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle lyricfier@0.2.1~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/zekunshen/Workspace/Collections/lyricfier/node_modules/.bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/zekunshen/.rvm/bin
8 verbose lifecycle lyricfier@0.2.1~prestart: CWD: /Users/zekunshen/Workspace/Collections/lyricfier
9 silly lifecycle lyricfier@0.2.1~prestart: Args: [ '-c', 'tsc' ]
10 silly lifecycle lyricfier@0.2.1~prestart: Returned: code: 2  signal: null
11 info lifecycle lyricfier@0.2.1~prestart: Failed to exec prestart script
12 verbose stack Error: lyricfier@0.2.1 prestart: `tsc`
12 verbose stack Exit status 2
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:877:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid lyricfier@0.2.1
14 verbose cwd /Users/zekunshen/Workspace/Collections/lyricfier
15 error Darwin 16.0.0
16 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 error node v7.0.0
18 error npm  v3.3.12
19 error code ELIFECYCLE
20 error lyricfier@0.2.1 prestart: `tsc`
20 error Exit status 2
21 error Failed at the lyricfier@0.2.1 prestart script 'tsc'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the lyricfier package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     tsc
21 error You can get their info via:
21 error     npm owner ls lyricfier
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

**Comment by emilioastarita** [comment]
Could you please post the output of run tsc manually in lyricifer dir:

node_modules/.bin/tsc

**Comment by drupalshift** [comment]
@emilioastarita here is the output of `node_modules/.bin/tsc` 

```
Lyricfier.ts(61,21): error TS2339: Property 'once' does not exist on type 'BrowserWindow'.
node_modules/@types/electron/index.d.ts(771,30): error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?
node_modules/@types/electron/index.d.ts(2568,21): error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?
node_modules/@types/electron/index.d.ts(2976,24): error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?
node_modules/@types/electron/index.d.ts(3697,21): error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

```

**Comment by emilioastarita** [comment]
I'm in vacations. Seems a problem with the types definitions but i think that the js are produced anyways. Try to run electron directly:

node_modules/.bin/electron . 

(Is important the last dot)

I'm back next month and i'll look at the compiler errors. Thanks for reporting and sorry for the delay.

**Comment by drupalshift** [comment]
@emilioastarita `node_modules/.bin/electron .` **does the trick , it's working** , gives this error but i think it's minor 

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'setAlwaysOnTop' of undefined
    at Lyricfier.alwaysOnTopSetup (/home/hamed/Downloads/lyricfier-master/Lyricfier.js:102:25)
    at /home/hamed/Downloads/lyricfier-master/Lyricfier.js:22:19
    at /home/hamed/Downloads/lyricfier-master/node_modules/async/dist/async.js:484:16
    at nextTask (/home/hamed/Downloads/lyricfier-master/node_modules/async/dist/async.js:5195:29)
    at /home/hamed/Downloads/lyricfier-master/node_modules/async/dist/async.js:5202:13
    at apply (/home/hamed/Downloads/lyricfier-master/node_modules/async/dist/async.js:41:25)
    at /home/hamed/Downloads/lyricfier-master/node_modules/async/dist/async.js:76:12
    at /home/hamed/Downloads/lyricfier-master/node_modules/async/dist/async.js:988:16
```

**Comment by leocaseiro** [comment]
> I'm in vacations. Seems a problem with the types definitions but i think that the js are produced anyways. Try to run electron directly:
> 
> node_modules/.bin/electron .
> 
> (Is important the last dot)
> 
> I'm back next month and i'll look at the compiler errors. Thanks for reporting and sorry for the delay.

@emilioastarita, running electron by itself works. I could see an alert, but the app still running and just work perfect :D

Here's a print of the alert error: 
![screen shot 2016-11-08 at 10 20 40 am 1](https://cloud.githubusercontent.com/assets/940070/20080313/2e462176-a59d-11e6-9c15-6021986c6cbf.png)

Thanks!!!

**Comment by jica** [comment]
It seems to be a problem with electron / node version.

From package.json:
```
  "devDependencies": {
    "@types/electron": "latest",
    "@types/electron-json-storage": "latest",
    "@types/node": "4.0.30",
    "@types/vue": "latest",
    "@types/mocha": "latest",
    "electron-builder": "^6.4.0",
    "electron-packager": "^7.7.0",
    "electron-prebuilt": "^1.2.0",
    "electron-zip-packager": "^3.0.0",
    "gulp": "^3.9.1",
    "gulp-less": "^3.1.0",
    "gulp-livereload": "^3.8.1",
    "typescript": "^2.0.0"
  }
```

I have changed node version to 'latest', getting the same result than executing electron directly:
```
$ npm start
> lyricfier@0.2.1 prestart /home/jica/git-projects/lyricfier
> tsc
> lyricfier@0.2.1 start /home/jica/git-projects/lyricfier
> electron .

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'setAlwaysOnTop' of undefined
    at Lyricfier.alwaysOnTopSetup (/home/jica/git-projects/lyricfier/Lyricfier.js:102:25)
    at /home/jica/git-projects/lyricfier/Lyricfier.js:22:19
    at /home/jica/git-projects/lyricfier/node_modules/async/dist/async.js:356:16
    at nextTask (/home/jica/git-projects/lyricfier/node_modules/async/dist/async.js:5057:29)
    at /home/jica/git-projects/lyricfier/node_modules/async/dist/async.js:5064:13
    at apply (/home/jica/git-projects/lyricfier/node_modules/async/dist/async.js:21:25)
    at /home/jica/git-projects/lyricfier/node_modules/async/dist/async.js:56:12
    at /home/jica/git-projects/lyricfier/node_modules/async/dist/async.js:840:16
    at /home/jica/git-projects/lyricfier/node_modules/electron-json-storage/lib/storage.js:90:14
    at nextTask (/home/jica/git-projects/lyricfier/node_modules/async/dist/async.js:5070:14)
```
I think that all 'latest' version should be changed to specific ones.

**Comment by emilioastarita** [comment]
fixed on master.
